#+TITLE: ООУ "Христо Узунов" - Другово
#+DESCRIPTION: Општинско основно училиште Христо Узунов од с. Другово, Кичево.
#+AUTHOR: А. Трајаноски
#+EXPORT_FILE_NAME: D:\My Drive\WEBSITE-HRISTOUZUNOV\index.html
#+SETUPFILE: D:\My Drive\WEBSITE-HRISTOUZUNOV\css\org\theme-readtheorg-local.setup
#+OPTIONS: num:nil


* Општи податоци за училиштето
ООУ "Христо Узунов" е основано со Одлука на Собранието на Општина Кичево на 01.09.1962 година. Училиштето има својство на правно лице и е запишано во судскиот регистер на Окружниот стопански суд - Скопје под ц. рег. 8262/94. Училиштето е раздружено од РО "11 Септември" 1992 година, а е потврдено со акт на Владата на Република Македонија 8262/94 од 23.04.1995 година и запишано во регистарот за основни училишта кај Министерството за образование и наука под број 10-21/6 од 28.04.1995 година. Седиштето на училиштето е во село Другово во чиј состав влегуваат и подрачните училишта во селата Србјани, Брждани и Подвис.

Во ООУ "Христо Узунов" – Другово, настава посетуваат ученици од прво до деветто и од селата кои гравитираат на територијата на поранешната општина Другово и тоа: Другово, Пополжани, Подвис, Добреноец, Брждани, Свињишта, Белица, Козица, Цер, Србјани и Манастирско Доленци.

До 16.08.1994 година   нашето училиште го носеше името  ЦОУ "Слобода", а потоа е преименувано во ЦОУ "Христо Узунов". Училиштето е збратимено со ОУ "Христо Узунов" - Охрид.

Од историското минато важно е да се напомене дека на територијата на поранешна општина Другово, односно во село Подвис на 30.09.1943 година започна со работа првото училиште на македонски мајчин јазик.

* Вработени
** Директор
*Билјана Анѓелеска - професор по одделенска настава*
** Стручни соработници
Стручните соработници во училиштето извршуваат разни активности во текот на учебната година како:
+ запишување на учениците и следење на нивниот развој во училиштето;
+ реализација на активности со учениците;
+ професионална ориентација/кариерен развој на учениците;
+ учество во планирање на воспитно-образовна работа на ниво на училиште;
+ поддршка во планирање и реализација на наставата;
+ поддршка на стручните активи на наставниците во избор и создавање на дидактички средства и материјали;
+ поддршка на наставниците за работа со учениците;
+ поддршка на наставниците за водење на педагошката документација и евиденција;
+ развивање на програми за унапредување на работата на училиштето (подобрување на резултатите и постигањата на учениците, инклузија, интеграција,интерклутура, демократско учество во работата на училиштето и сл.);
+ развивање постапки и инструменти за следење и вреднување на постигањата на учениците и самовреднување на училиштето;
+ учество во планирање, организирање и реализација на сопствениот професионален развој и на професионалниот развој на воспитно-образовниот кадар во училиштето, соработка и работа со родители/старатели;
+ поддршка на работата на училишна заедница на учениците;
+ примена на прописите за остварување на правата и должностите на учениците, напредувањето и изрекувањето на педагошки мерки;
+ организирање на педагошка и методска практика на студенти;
+ организирање и водење на работата на училишната библиотека;
+ водење на професионални досиеја и
+ вршење на други работи определени со годишната програма за работа.

|   | Име     | Презиме     | Раб. место  | Профил на НПУД      |
|---+---------+-------------+-------------+---------------------|
| 1 | Оливера | Е. Илиевска | Педагог     | oe461691@schools.mk |
| 2 | Јасмина | Дејаноска   | Психолог    | jd191027@schools.mk |
| 3 | Дафинка | Сталеска    | Библиотекар | ds198116@schools.mk |

** Наставен кадар
*** Одделенска настава
#+begin_src
ЦЕНТРАЛНО УЧИЛИШТЕ
#+end_src

|   | Име      | Презиме    | Одделение | Профил на НПУД      |
|---+----------+------------+-----------+---------------------|
| 1 | Жаклина  | Стојаноска | Прво      | zs924093@schools.mk |
| 2 | Светлана | Ѓорѓијоска | Второ     | sg450149@schools.mk |
| 3 | Милчо    | Данилоски  | Трето     | md669671@schools.mk |
| 4 | Зоран    | Арминовски | Четврто   | za418488@schools.mk |
| 5 | Сузана   | Данилоска  | Петто     | sd671205@schools.mk |

*Подрачни училишта*

#+begin_src
ПУ БРЖДАНИ (Комбинирана паралелка од I, II, IV и V)
#+end_src

|   | Име      | Презиме          | Одделение     | Предмет              | Профил на НПУД      |
|---+----------+------------------+---------------+----------------------+---------------------|
| 1 | Катерина | Петреска Миноска | I, II, IV и V | Одделенска настава   | kp561504@schools.mk |
| 2 | Билјана  | Костески         | I, II, IV и V | Англиски јазик       | /                   |
| 3 | Дејан    | Стојкоски        | IV и V        | Природни науки       | ds184025@schools.mk |
| 4 | Владимир | Сарџоски         | I и II        | ФЗО                  | vs706914@schools.mk |
| 5 | Борче    | Никоски          | V             | Техничко образование | /                   |

#+begin_src
ПУ СРБЈАНИ (Комбинирана паралелка од I, II, III и IV)
#+end_src

|   | Име      | Презиме   | Одделение       | Предмет            | Профил на НПУД      |
|---+----------+-----------+-----------------+--------------------+---------------------|
| 1 | Јулијана | Штерјоска | I, II, III и IV | Одделенска настава | js183861@schools.mk |
| 2 | Билјана  | Костески  | I, II, III и IV | Англиски јазик     | /                   |
| 3 | Дејан    | Стојкоски | IV              | Природни науки     | ds184025@schools.mk |
| 4 | Владимир | Сарџоски  | I, II и III     | ФЗО                | vs706914@schools.mk |

#+begin_src
ПУ ПОДВИС (Една паралелка во V одделение)
#+end_src
|   | Име     | Презиме   | Одделение | Предмет              | Профил на НПУД      |
|---+---------+-----------+-----------+----------------------+---------------------|
| 1 | Јованка | Алексоска | V         | Одделенска настава   | js183861@schools.mk |
| 2 | Биљана  | Алексоска | V         | Англиски јазик       | ba447398@schools.mk |
| 3 | Дејан   | Стојкоски | V         | Природни науки       | ds184025@schools.mk |
| 4 | Борче   | Никоски   | V         | Техничко образование | /                   |

*Совет на одделенски наставници*

Советот на одделенските наставници го сочинуваат одделенските наставници, предметните наставници кои се вклучуваат во реализацијата на наставата од прво до петто одделение и стручните соработници на училиштето.
Советот на одделенските наставници ги разгледува годишната програма за работа и планирањето на наставата, воспитно-образовните проблеми по одделенија, подготвува програма за работа со талентираните ученици, односно за учениците кои потешко напредуваат, предлага и одлучува за воспитните мерки и врши други работи утврдени во статутот на училиштето.

*** Предметна настава

|    | Име        | Презиме      | Предмет              | Профил на НПУД       |
|----+------------+--------------+----------------------+----------------------|
|  1 | Ивана      | Витанска     | Македонски јазик     | iv2030305@schools.mk |
|  2 | Јоше       | Спасески     | Македонски јазик     | js2503265@schools.mk |
|  3 | Јасминка   | Јованоска    | Математика           | jj1552735@schools.mk |
|  4 | Александра | Костадиноска | Математика и физика  | ak2397095@schools.mk |
|  5 | Елисавета  | С. Делевска  | Англиски јазик       | es2161685@schools.mk |
|  6 | Биљана     | Алексоска    | Англиски јазик       | ba4473985@schools.mk |
|  7 | Катерина   | Лазороска    | Германски јазик      | kl962037@schools.mk  |
|  8 | Илче       | Ѓорески      | Ликовно образование  | /                    |
|  9 | Христиан   | Тришоски     | Музичко образование  | kt8283635@schools.mk |
| 10 | Дејан      | Стојкоски    | Природни науки       | ds1840255@schools.mk |
| 11 | Борче      | Никоски      | Техничко образование | /                    |
| 12 | Александар | Трајаноски   | Информатика          | at146825@schools.mk  |
| 13 | Светлана   | М. Трпеска   | Географија           | sg4501495@schools.mk |
| 14 | Виолета    | Петкоска     | Историја             | vp4066195@schools.mk |
| 15 | Размена    | Стојкоска    | Биологија и хемија   | rs2562365@schools.mk |
| 16 | Миланка    | Ж. Цветкоска | ФЗО                  | mz3419265@schools.mk |
| 17 | Владимир   | Сарџоски     | ФЗО                  | vs7069145@schools.mk |

*Совет на предметни наставници*

Советот на предметните наставници го сочинуваат предметните наставници што ја изведуваат наставата од шесто до деветто одделение и стручните соработници на училиштето.
Советот на предметните наставници ги разгледува годишната програма за работа и планирањето на наставата, воспитно-образовните проблеми по одделенија, подготвува програма за работа со талентираните ученици, односно со оние кои потешко напредуваат, одлучува за воспитните мерки и врши други работи утврдени во статутот на училиштето. Одделенскиот, односно раководителот на паралелката ја остварува програмата за часот на одделенската заедница, ги анализира воспитните и наставните резултати на одделението, се грижи за решавање на воспитните и наставните проблеми на одделни ученици, соработува со родителите и стручните соработници на училиштето, предлага и одлучува за воспитните мерки и врши други работи утврдени во статутот на училиштето.

** Наставнички совет
Наставничкиот совет на основното училиште го сочинуваат одделенските и предметните наставници и стручните соработници на училиштето.
Наставничкиот совет го свикува и со него претседава *директорот*.

Наставничкиот совет на основното училиште ги извершува следните активности:
+ Дава мислења по предлогот на прогамата за развој и на годишната програма за работа и го следи нејзиното извршување;
+ Го разгледува и утврдува успехот на учениците и работата на други стручни органи;
+ Им одобрува на учениците побрзо напредување во основното училиште;
+ Го разгледува остварувањето на наставниот план и програмите и презема мерки за нивно извршување;
+ Донесува одлуки по приговори на учениците за утврдени оценки;
+ Го разгледува извештајот од реализација на годишната програма за работа, од самоевалуација, од извршената интегрална евалуација и предлага соодветни мерки, расправа и одлучува за стручни прашања поврзани со воспитно-образовната работа;
+ Дава мислење за годишниот финансиски план на училиштето;
+ Избира претставници во училишниот одбор;
+ Дава мислење за планирањето, реализацијата и вреднувањето на постигањата во наставата и учењето;
+ Го разгледува годишниот извештај за работа на наставниците и стручните соработници и Националниот извештај за работа на наставниците и стручните соработници и предлага соодветни мерки;
+ Дава предлози за напредување на наставниците и стручните соработници на училиштето;
+ Одлучува за воспитни мерки; и
+ Други работи утврдени во статутот на училиштето.

* Органи на училиштето
** Училишен одбор

Орган на управување на основното училиште е училишниот одбор.
Училишниот одбор на основното училиште е составен од седум члена, и тоа: тројца претставници од наставниците, стручните соработници и воспитувачите од училиштето, тројца претставници од родителите на учениците и еден претставник од основачот.
Мандатот на членовите на училишниот одбор е три години, а мандатот на претставниците на родителите е за период до завршување на основното образование на нивното дете, но не подолго од три години.
Училишниот одбор од редот на своите членови избира претседател со мнозинство гласови од вкупниот број членови, по пат на тајно гласање.
Одлуките на училишниот одбор се донесуваат со мнозинство гласови од вкупниот број членови.

Училишниот одбор на основното училиште ги извршува следните активности:

+ Донесува статут на основното училиште;
+ Предлага годишна програма за работа и извештај за работа на основното училиште до советот на општината;
+ Донесува програма за развој на училиштето;
+ Донесува програма за воведување на повисоки стандарди и други програми;
+ Предлага финансиски план до основачот;
+ Предлага завршна сметка до основачот;
+ Објавува јавен оглас за избор на директор во најмалку три дневни весници кои се издаваат на целата територија на Република Македонија од кои еден од весниците кој се издава на јазикот што го зборуваат најмалку 20% од граѓаните кои зборуваат службен јазик различен од македонскиот јазик;
+ Врши интервју со кандидатите за директор;
+ Предлага на градоначалникот на општината еден, односно двајца кандидати од пријавените кандидати на објавениот јавен оглас за избор на директор;
+ Дава мислење до директорот за избор на наставниците, стручните соработници и воспитувачите;
+ Поднесува предлог до директорот за престанок на работниот однос на лицата;
+ Одлучува по приговорите и жалбите на вработените во основното училиште;
+ Одлучува по жалбите на ученици, родители, односно старатели на ученици; и
+ Други работи утврдени со статутот на основното училиште.

  |   | Име     | Презиме    | Преставник од     | Функција    |
  |---+---------+------------+-------------------+-------------|
  | 1 | Дејан   | Стојкоски  | наставен кадар    | претседател |
  | 2 | Жаклина | Стојаноска | наставен кадар    | член        |
  | 3 | Јованка | Алексоска  | наставен кадар    | член        |
  | 4 | Слаѓана | Јованоска  | совет на родители | член        |
  | 5 | Билјана | Миноска    | совет на родители | член        |
  | 6 | Гордана | Спасеноска | совет на родители | член        |
  | 7 | Анета   | Сарџоска   | општина           | член        |

** Совет на родители
Советот на родителите делува во рамките на соработката на училишетето со родителите,заради разгледување на прашања од заеднички интерес за работата на училишетето и учениците, како и прашања поврзани со реализацијата на процесот на воспитнообразовнатата работа во училиштето.
Бројот на членовите на Советот на родителите зависи од бројот на паралелките во училиштето. Преставникот од секоја паралелка го избират родителите на родителски состанок на паралелката во месец Септември односно со почетокот на учебната година, со мнозинство гласови од вкупниот број на родители на учениците од паралелката.

Советот на родителите:

+ Дава мислење предлог програмата на училиштето и за годишната програма за работа на учлиштето;
+ Расправа за извештајот за работата на училиштето како и за подобрување на успехот и поведението на учениците;
+ Предлага програми за подобрување на стандардите во наставата;
+ Дава согласност на предлозите на директорот за воведување на повисоки стандарди;
+ Организитање на јавниот и културниот живот на учениците,спортски и други манифестации,заштита на животната средина во училиштето и надвор од него;
+ Разгледува жалби на родителите во врска со воспитно-образовната работа;
+ Избира тројца преставници во училишниот одбор, со непосредно и тајно гласање;
+ Дава мислење за екскурзиите,настава во природа и планот за нивна реализација,кој неможе да се реализира доколку мислењето на Советот не е позитивно;
+ Ги организира другите родители за учество и реализација на јавниот и културниот живот на училиштето;
+ Ги ангажира родителите за собирање на финансиски средства за обновување на инвентарот,опремување на училиштето,помагање на ученици-социјални случаи и сл.;
+ Активно учествува во реализација во меѓучилишната соработка во градот и надвор од него;
+ Донесува одлуки за реализација на финансиските проблеми околу одржување на училиштето;
+ Дава предлози и мислења до Наставничкиот совет и до Училишниот одбор за други прашања што се од интерес за учениците и училиштето.

** Ученички парламент

Заедницата на учениците е значаен сегмент во организиацијата на животот и работата во училиштето. Заедницата на учениците е организирана во сите паралелки од петто до деветто одделение, а по правило учениците избираат претставници на заедницата на паралелката кои ќе учествуваат во работата на Ученичкиот парламент. Ученичкиот парламент ги сочинуваат претседателите на заедниците на паралелките.Првото свикување на ученичкиот парламент го врши директорот на училиштето.

Претседателот на Ученичкиот парламент се избира со мнозинство гласови од вкупниот број на претставници од претсдателите на заедниците на паралелките по пат на тајно гласање
Ученичкиот првобранител се грижи за заштита и унапредување на правата на учениците во училиштето.
Ученичкиот правобранител се избира со мнозинство гласови од учениците од седмо до деветто одделение по пат на тајно гласање.

Ученичкиот парламент ги извршува следните активности:
+ Активно учествува во застапување и промовирање на правата и интересите на учениците;
+ Го промовира ученичкиот активизам;
+ Учествува во активности за обезбедување врсничка поддршка на учениците со посебни образовни потреба и во реализацијата на наставата и слободните активности;
+ Учествува во подготовката на Годишната програма за работа;
+ Дава предлог активности за годишни програми за екскурзии;
+ Дава предлози за воннаставни активности на училиштето;
+ Дава предлози за подобрување на ученичкиот стандард;
+ Учествува во евалуацијата на работата на училиштето;
+ Преку свои претставници учествува во Советот на родители и Наставничкиот совет;
+ Органзира и учествуваат во хуманитарни активности, еколошки активности и опшествено корисна работа.

* Организација на настава
Организирањето на учебната година и одморите на учениците се утврдуваат со Календарот за организација и работа на училиштето во согласност со [[https://mon.gov.mk/stored/document/Kalendar%202021-2022.pdf][Календарот за организација и работа на основните училишта]].
Учебната 2020/2021 година ќе започне на 01.09.2021 година, а ќе трае до 31.08.2022 година.
Наставната година започнува на 1 септември 2021 година и завршува на 9 јуни 2022 година.
ООУ “Христо Узунов” с. Другово ќе работи во две смени и тоа:

1. Во првата смена учениците од шесто до деветто одделение
   - [[https://docs.google.com/document/d/1hK28EkvXHie3InVKVtJDrm08OvTMd__q/edit?usp=sharing&ouid=114031635415672922421&rtpof=true&sd=true][Распоред на часови]]
   - [[https://docs.google.com/document/d/1OBOajn8cnolwc-L6h7uEAq8ISKaZ1jt-/edit?usp=sharing&ouid=114031635415672922421&rtpof=true&sd=true][Распоред за додатна и дополнителна настава по предмети]]
   - [[https://docs.google.com/document/d/1AlpMUMHbOeWl9R5-ERsAcwiUNcNiyypc/edit?usp=sharing&ouid=114031635415672922421&rtpof=true&sd=true][Распоред за додатна и дополнителна настава по денови]]
2. Во втората смена учениците од прво до петто одделение и подготвителната година.


+ [[https://mon.gov.mk/stored/document/Protokol%20osnovno%202021-2022%20mk_1.pdf][Протокол за постапување на основните училишта во Р. Северна Македонија за реализација на воспитно - образовниот процес со физичко присуство на учениците во учебната 2021/22 година.]]
+ [[https://mon.gov.mk/stored/document/Plan%20za%20odrzuvane%20nastava%20vo%20osnovno%20i%20sredno%20obrazovanie%202021%202022_2.pdf][План за одржување на наставата во основните училишта во учебната 2021/22 година.]]
+ [[https://mon.gov.mk/stored/document/standardi-USVOENI.pdf][Национални стандарди за постигањата на учениците]]

* Податоци за бројот на ученици

|           |  I | II | III | IV |  V | I-V | VI | VII | VIII | IX | VI-IX | I-IX |
|-----------+----+----+-----+----+----+-----+----+-----+------+----+-------+------|
| Централно | 12 | 13 |   7 | 11 | 13 |  56 | 18 | 13  | 13   | 20 | 64    |  120 |
| Брждани   |  1 |  1 |   0 |  2 |  2 |   6 | /  | /   | /    | /  | /     |    6 |
| Србјани   |  7 |  1 |   2 |  1 |  0 |  11 | /  | /   | /    | /  | /     |   11 |
| Подвис    |  0 |  0 |   0 |  0 |  2 |   2 | /  | /   | /    | /  | /     |    2 |
|-----------+----+----+-----+----+----+-----+----+-----+------+----+-------+------|
| ВКУПНО    | 20 | 15 |   9 | 14 | 17 |  75 | 18 | 13  | 13   | 20 | 64    |  139 |

* Документи

| Опис                     | Линк    |
|--------------------------+---------|
| Статут на училиштето     | [[https://docs.google.com/document/d/1ugyFNWbLR_aXtKQXjAFWiOwWre5MYM5s/edit?usp=sharing&ouid=114031635415672922421&rtpof=true&sd=true][Преглед]] |
| Годишна програма 2021/22 | [[https://docs.google.com/document/d/1xAg4ZfYzNp-tG2P_8-ZwUjfYiq7jUA-K/edit?usp=sharing&ouid=114031635415672922421&rtpof=true&sd=true][Преглед]] |
| Самоевалуација 2021      | [[https://docs.google.com/document/d/1-K9NnnYlt3ZDrA2ycbxraU0fxGcLxGgp/edit?usp=sharing&ouid=114031635415672922421&rtpof=true&sd=true][Преглед]] |

* Е-Училиште
| Опис                                      | Линк       |
|-------------------------------------------+------------|
| Национална платформа за учење на далечина | [[https://lms.schools.mk/][НУПД]]       |
| Microsoft Office 365                      | [[https://www.office.com][Office 365]] |
| Електронски дневник                       | [[https://ednevnik.edu.mk/][E-Дневник]]  |
| Електронски учебници                      | [[https://www.e-ucebnici.mon.gov.mk/][Е-учебници]] |
| Едуино настава                            | [[http://www.eduino.gov.mk/][Eдуино]]     |
| Распоред на часови на МРТВ (Основно)      | [[https://mon.gov.mk/content/?id=3365][Распоред]]   |

| Опис                                | Линк |
|-------------------------------------+------|
| Министерство за образование и наука | [[https://mon.gov.mk/][МОН]]  |
| Биро за развој на образованието     | [[https://www.bro.gov.mk/][БРО]]  |


* Соопштенија
#+begin_src
31.9.2021
#+end_src

Им се соопштува на сите ученици од I до IX одделение дека оваа учебна година наставата ќе започне со физичко присуство со почитување на пропишаните протоколи за заштита од COVID-19.
* За патронот на училиштето

*Христо Димитров Узунов* или познат како Арсениј, Арсо, Дуле, Маглата, Ристо, Самуил или Дуле Узунов (Охрид, 22 октомври 1878 – Цер, 24 април 1905 — македонски револуционер, учител, војвода и реонски началник на четите на Македонската револуционерна организација во Охридскиот револуционерен округ. Се школувал во Солун и учествувал во солунските училишни бунтови (1896). Лежел во битолскиот Централен затвор Катилане (1898 и 1902–1903). Од 1903 година бил поставен за главен војвода на охридските револуционерни чети. Учествувал на Смилевскиот конгрес. Во Илинденското востание бил член на Горското началство (Штабот) за Охридскиот револуционерен реон. Учествувал во спасувањето на збегот од Рашанец на ок. 200 семејства. На Прилепскиот конгрес бил избран за секретар и за окружен ревизор на четите на МРО за Охридско, Струшко и Кичевско. Загинал со четата опколен од турска војска.

Татко му Димитар Узунов бил долгогодишен учител и борец за независна црква, близок и роднина на Григор Прличев, а неговата мајка Анастасија Узунов потекнува од стариот струшки просветистелски род Чакарови, таа е ќерка на Георги Чакаров, и е прва братучетка на Христо Матов и Милан Матов. Христо Узунов, заедно со двајцата свој помали браќа Андон и Ангел (исто така дејци на Македонската револуционерна организација) бил воспитуван од мајка си во патриотски дух.

*Писмо до неговата мајка*

    /Мила ми мајко, Јас сум прв твој син и мој долг е да бидам околу тебе, за да не чувствуваш потреба од ништо. За твојата беспределна љубов, за илјадите неволи и сраданија, за безбројните бессони и машителни ноќи, поминати некогаш над леглото над твојот мал, слабичок Луле, јас должам најголеми грижи и неизмерна синовска љубов. Но, можам ли, кога ги чувствуам болките на нашата измачена Татковина, да не се оддадам со љубов на најверен син на нејзиното свето дело? - Маките на татковината се повеќе од сите страданија на секоја наша мајка. И јас - без ни најмалку да те навредувам - се чувствувам повеќе син на втората моја мајка - Македонија, отколку на тебе, која си ме родила. Те молам - во името пак на моите свети чувства кон тебе - да не жалиш, ни да плачеш за мене. Најдоволен ќе се чувствувам, ако ти со своето држење бидеш за пример на другите мајки и сопруги./

*Песна за Христо Узунов*

Неговата херојска смрт е опеана во /Песна за Христо Узунов/

/И таму е мојта родина,/ \\
/далеку Македонија,/ \\
/јас сакам таму да загинам,/ \\
/а ти ме забрави за век.../ \\
/...Не жали мила моја родино,/ \\
/и сите ми другари мој,/ \\
/ако Христо Узунов падна,/ \\
/на врагот жив не се даде./ \\
